local C = {
	DOG_SCALE = 0.25,
	DOG_SPEED = 250,
	EVIL_CLOSE_SPEED = 50,
	EGG_DOG_SPEED = 100,
	EVIL_CLOSE_SCALE = 0.40,
	WINDOW_WIDTH = 1600,
	WINDOW_HEIGHT = 900,
	VOLUME = 0.25,
	TOPOFFSET = 72,
	VIDEO_W = 368,
	VIDEO_H = 312,
	SPAWN_MIN = 1.0,
	SPAWN_MAX = 4.0,
	POPUP_TTL_MIN = 6.0,
	POPUP_TTL_MAX = 12.0,
	MAX_POPUPS = 8,
	BULLET_TTL = 25,
	EGG_BULLET_SCALE = 0.25,
	EGG_BULLET_SPEED = 150,
	BUTTER_BULLET_SPEED = 900,
	BUTTER_BULLET_SCALE = 0.5,
	LOADING_TIME = 13.24,
	GAME_TIME_LENGTH = 212,
	GAME_TIME_BOSS_START = 133,
	-- boss attack tuning
	XIAO_LASER_COOLDOWN = 4.0,
	XIAO_LASER_DURATION = 1.5,
	XIAO_LASER_RATE = 0.06, -- seconds between laser shots
	XIAO_SPREAD_COOLDOWN = 3.5,
	XIAO_SPREAD_COUNT = 10,
	XIAO_SPREAD_ANGLE = math.rad(90), -- total spread in radians
	DOG_SPAWN_RATE = 1.15,
	VIDEO_SPAWN_RATE = 0.75,
	-- LOADING_TIME = 0.05, -- for debug
	-- UNKILLABLE = true, -- for debug
}

return C
